# coding: utf-8

"""
    Notes API

    Manage your notes in a simple way.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.note_paging import NotePaging  # noqa: E501
from swagger_client.rest import ApiException


class TestNotePaging(unittest.TestCase):
    """NotePaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotePaging(self):
        """Test NotePaging"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.note_paging.NotePaging()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
