# coding: utf-8

"""
    Notes API

    Manage your notes in a simple way.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.note_post import NotePost  # noqa: E501
from swagger_client.rest import ApiException


class TestNotePost(unittest.TestCase):
    """NotePost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotePost(self):
        """Test NotePost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.note_post.NotePost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
