# coding: utf-8

"""
    Notes API

    Manage your notes in a simple way.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.folder_post import FolderPost  # noqa: E501
from swagger_client.rest import ApiException


class TestFolderPost(unittest.TestCase):
    """FolderPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFolderPost(self):
        """Test FolderPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.folder_post.FolderPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
