# coding: utf-8

"""
    Notes API

    Manage your notes in a simple way.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.folder_api import FolderApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFolderApi(unittest.TestCase):
    """FolderApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.folder_api.FolderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_folder_id_view(self):
        """Test case for delete_folder_id_view

        """
        pass

    def test_get_folder_view(self):
        """Test case for get_folder_view

        """
        pass

    def test_post_folder_view(self):
        """Test case for post_folder_view

        """
        pass

    def test_put_folder_id_view(self):
        """Test case for put_folder_id_view

        """
        pass


if __name__ == '__main__':
    unittest.main()
