# coding: utf-8

"""
    Notes API

    Manage your notes in a simple way.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.note_api import NoteApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNoteApi(unittest.TestCase):
    """NoteApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.note_api.NoteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_note_id_view(self):
        """Test case for delete_note_id_view

        """
        pass

    def test_get_note_view(self):
        """Test case for get_note_view

        """
        pass

    def test_post_folder_note_view(self):
        """Test case for post_folder_note_view

        """
        pass

    def test_put_note_id_view(self):
        """Test case for put_note_id_view

        """
        pass


if __name__ == '__main__':
    unittest.main()
