# coding: utf-8

"""
    Notes API

    Manage your notes in a simple way.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class NotePaging(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'has_next': 'bool',
        'has_prev': 'bool',
        'items': 'list[Note]',
        'next_num': 'int',
        'pages': 'int',
        'per_page': 'int',
        'prev_num': 'int',
        'total': 'int'
    }

    attribute_map = {
        'has_next': 'has_next',
        'has_prev': 'has_prev',
        'items': 'items',
        'next_num': 'next_num',
        'pages': 'pages',
        'per_page': 'per_page',
        'prev_num': 'prev_num',
        'total': 'total'
    }

    def __init__(self, has_next=None, has_prev=None, items=None, next_num=None, pages=None, per_page=None, prev_num=None, total=None, _configuration=None):  # noqa: E501
        """NotePaging - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._has_next = None
        self._has_prev = None
        self._items = None
        self._next_num = None
        self._pages = None
        self._per_page = None
        self._prev_num = None
        self._total = None
        self.discriminator = None

        if has_next is not None:
            self.has_next = has_next
        if has_prev is not None:
            self.has_prev = has_prev
        if items is not None:
            self.items = items
        if next_num is not None:
            self.next_num = next_num
        if pages is not None:
            self.pages = pages
        if per_page is not None:
            self.per_page = per_page
        if prev_num is not None:
            self.prev_num = prev_num
        if total is not None:
            self.total = total

    @property
    def has_next(self):
        """Gets the has_next of this NotePaging.  # noqa: E501


        :return: The has_next of this NotePaging.  # noqa: E501
        :rtype: bool
        """
        return self._has_next

    @has_next.setter
    def has_next(self, has_next):
        """Sets the has_next of this NotePaging.


        :param has_next: The has_next of this NotePaging.  # noqa: E501
        :type: bool
        """

        self._has_next = has_next

    @property
    def has_prev(self):
        """Gets the has_prev of this NotePaging.  # noqa: E501


        :return: The has_prev of this NotePaging.  # noqa: E501
        :rtype: bool
        """
        return self._has_prev

    @has_prev.setter
    def has_prev(self, has_prev):
        """Sets the has_prev of this NotePaging.


        :param has_prev: The has_prev of this NotePaging.  # noqa: E501
        :type: bool
        """

        self._has_prev = has_prev

    @property
    def items(self):
        """Gets the items of this NotePaging.  # noqa: E501


        :return: The items of this NotePaging.  # noqa: E501
        :rtype: list[Note]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this NotePaging.


        :param items: The items of this NotePaging.  # noqa: E501
        :type: list[Note]
        """

        self._items = items

    @property
    def next_num(self):
        """Gets the next_num of this NotePaging.  # noqa: E501


        :return: The next_num of this NotePaging.  # noqa: E501
        :rtype: int
        """
        return self._next_num

    @next_num.setter
    def next_num(self, next_num):
        """Sets the next_num of this NotePaging.


        :param next_num: The next_num of this NotePaging.  # noqa: E501
        :type: int
        """

        self._next_num = next_num

    @property
    def pages(self):
        """Gets the pages of this NotePaging.  # noqa: E501


        :return: The pages of this NotePaging.  # noqa: E501
        :rtype: int
        """
        return self._pages

    @pages.setter
    def pages(self, pages):
        """Sets the pages of this NotePaging.


        :param pages: The pages of this NotePaging.  # noqa: E501
        :type: int
        """

        self._pages = pages

    @property
    def per_page(self):
        """Gets the per_page of this NotePaging.  # noqa: E501


        :return: The per_page of this NotePaging.  # noqa: E501
        :rtype: int
        """
        return self._per_page

    @per_page.setter
    def per_page(self, per_page):
        """Sets the per_page of this NotePaging.


        :param per_page: The per_page of this NotePaging.  # noqa: E501
        :type: int
        """

        self._per_page = per_page

    @property
    def prev_num(self):
        """Gets the prev_num of this NotePaging.  # noqa: E501


        :return: The prev_num of this NotePaging.  # noqa: E501
        :rtype: int
        """
        return self._prev_num

    @prev_num.setter
    def prev_num(self, prev_num):
        """Sets the prev_num of this NotePaging.


        :param prev_num: The prev_num of this NotePaging.  # noqa: E501
        :type: int
        """

        self._prev_num = prev_num

    @property
    def total(self):
        """Gets the total of this NotePaging.  # noqa: E501


        :return: The total of this NotePaging.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this NotePaging.


        :param total: The total of this NotePaging.  # noqa: E501
        :type: int
        """

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NotePaging, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NotePaging):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NotePaging):
            return True

        return self.to_dict() != other.to_dict()
