# coding: utf-8

"""
    Notes API

    Manage your notes in a simple way.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Note(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'folder_id': 'int',
        'type': 'int',
        'is_public': 'bool',
        'items': 'list[NoteItem]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'folder_id': 'folder_id',
        'type': 'type',
        'is_public': 'is_public',
        'items': 'items'
    }

    def __init__(self, id=None, name=None, folder_id=None, type=None, is_public=None, items=None, _configuration=None):  # noqa: E501
        """Note - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._folder_id = None
        self._type = None
        self._is_public = None
        self._items = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if folder_id is not None:
            self.folder_id = folder_id
        if type is not None:
            self.type = type
        if is_public is not None:
            self.is_public = is_public
        if items is not None:
            self.items = items

    @property
    def id(self):
        """Gets the id of this Note.  # noqa: E501


        :return: The id of this Note.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Note.


        :param id: The id of this Note.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Note.  # noqa: E501


        :return: The name of this Note.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Note.


        :param name: The name of this Note.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def folder_id(self):
        """Gets the folder_id of this Note.  # noqa: E501


        :return: The folder_id of this Note.  # noqa: E501
        :rtype: int
        """
        return self._folder_id

    @folder_id.setter
    def folder_id(self, folder_id):
        """Sets the folder_id of this Note.


        :param folder_id: The folder_id of this Note.  # noqa: E501
        :type: int
        """

        self._folder_id = folder_id

    @property
    def type(self):
        """Gets the type of this Note.  # noqa: E501


        :return: The type of this Note.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Note.


        :param type: The type of this Note.  # noqa: E501
        :type: int
        """

        self._type = type

    @property
    def is_public(self):
        """Gets the is_public of this Note.  # noqa: E501


        :return: The is_public of this Note.  # noqa: E501
        :rtype: bool
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public):
        """Sets the is_public of this Note.


        :param is_public: The is_public of this Note.  # noqa: E501
        :type: bool
        """

        self._is_public = is_public

    @property
    def items(self):
        """Gets the items of this Note.  # noqa: E501


        :return: The items of this Note.  # noqa: E501
        :rtype: list[NoteItem]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this Note.


        :param items: The items of this Note.  # noqa: E501
        :type: list[NoteItem]
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Note, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Note):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Note):
            return True

        return self.to_dict() != other.to_dict()
